### ISSUE TITLE
error checking design considerations

### ISSUE THREAD

**Issue by hokagejack** [BCaven/creativity-optional#36]
On line 79 in the process_command function under local_misc_client.py you could change the assertion statement. 

Assert is really only used for debugging so I wouln't think you would want to use it for input validation in this case. 

Instead, you could replace it with something like this

if not isinstance(command, (str, list)):
        raise TypeError(f"invalid command type {type(command)}: only str and list are allowed")

**Comment by BCaven** [comment]
`process_command` is an internal function that the user never interacts with directly.
In other words, that assert statement *is* only there for debugging.

I think it would be valid to replace the assert on line `138` with a if/raise block.
In general I gravitate towards assert statements because you can tell python to run without them (the experienced user might want the extra speed if they know their setup works as intended).
The assert statements are mostly there for future developers and are not super useful for the end user.
For end users it might be better to use log messages instead of actual python errors so the program gracefully closes instead of crashing. That way we can also work around bad inputs instead of crashing when encountering one.
